version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: monblog
      POSTGRES_USER: monblog
      POSTGRES_PASSWORD: monblogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./blog-backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://monblog:monblogpassword@postgres:5432/monblog
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./blog-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      PORT: 3001
    ports:
      - "3001:3001"

volumes:
  postgres-data: