import { RoleName } from "./roles.constants";

export const Permissions = {
  [RoleName.PRIMARY_ADMIN]: {
    canManageArticles: true,
    canModerateAll: true,
    canModerateMembers: true,
    canPromoteMembers: true,
    canDeleteAdmins: true,
    canManageOwnArticles: true,
    canViewOwnStats: true,
    canDeleteCommentsOnOwnArticles: true,
    canModerateCommentsOnOwnArticles: true,
    canComment: true,
    isProtected: true,
  },
  [RoleName.SECONDARY_ADMIN]: {
    canManageArticles: true,
    canModerateMembers: true,
    canModerateAll: false,
    canPromoteMembers: false,
    canDeleteAdmins: false,
    canManageOwnArticles: true,
    canViewOwnStats: true,
    canDeleteCommentsOnOwnArticles: true,
    canModerateCommentsOnOwnArticles: true,
    canComment: true,
    isProtected: false,
  },
  [RoleName.MEMBER]: {
    canManageArticles: false,
    canModerateAll: false,
    canModerateMembers: false,
    canPromoteMembers: false,
    canDeleteAdmins: false,
    canManageOwnArticles: true,
    canViewOwnStats: true,
    canDeleteCommentsOnOwnArticles: true,
    canModerateCommentsOnOwnArticles: true,
    canComment: true,
    isProtected: false,
  },
  [RoleName.SIMPLE_USER]: {
    canManageArticles: false,
    canModerateAll: false,
    canModerateMembers: false,
    canPromoteMembers: false,
    canDeleteAdmins: false,
    canManageOwnArticles: false,
    canViewOwnStats: false,
    canDeleteCommentsOnOwnArticles: false,
    canModerateCommentsOnOwnArticles: false,
    canComment: true,
    isProtected: false,
  },
};
